[run]
  deadline = "10m"
  tests = true

 [ linters-settings.custom.terraform-schema-ordering ]
    path = "/Users/matthewlin/go/src/github.com/Terraform-Schema-Ordering/terraform-schema-ordering.so"
    description = "asd"

[linters]
  disable-all = true
  enable = [
    "gofmt",
    "goimports",
    "deadcode",
    "gosimple",
    "govet",
    "ineffassign",
    "structcheck",
    "unconvert",
    "unused",
    "varcheck",
    "terraform-schema-ordering",
  ]
